# Copyright © 2019 State Street Bank and Trust Company.  All rights reserved
#
# SPDX-License-Identifier: Apache-2.0

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/protoc-plugin
    docker:
      - image: cimg/openjdk:17.0
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: |
            ./lein deps
      - run: make all
      - run: |
          mkdir tmp
          mv target/protoc-gen-clojure tmp
      - store_artifacts:
          path: tmp/
          destination: bin
